TRUNCATE TABLE AIRFLOW0105.STAGING.STG_STOCK_HISTORY_4;
INSERT INTO AIRFLOW0105.STAGING.STG_STOCK_HISTORY_4
SELECT * FROM US_STOCK_DAILY.DCCM.STOCK_HISTORY;

TRUNCATE TABLE AIRFLOW0105.STAGING.STG_COMPANY_PROFILE_4;
INSERT INTO AIRFLOW0105.STAGING.STG_COMPANY_PROFILE_4
SELECT * FROM US_STOCK_DAILY.DCCM.COMPANY_PROFILE;

TRUNCATE TABLE AIRFLOW0105.STAGING.STG_SYMBOLS_4;
INSERT INTO AIRFLOW0105.STAGING.STG_SYMBOLS_4
SELECT * FROM US_STOCK_DAILY.DCCM.SYMBOLS;