UPDATE AIRFLOW0105.DEV.ETL_METADATA_4
SET
  LAST_LOADED_DATE = (
    SELECT MAX(DATE) FROM AIRFLOW0105.STAGING.STG_STOCK_HISTORY_4
  ),
  IS_INITIALIZED = TRUE,
  LAST_RUN_TS = CURRENT_TIMESTAMP()
WHERE JOB_NAME = 'stock_etl';