UPDATE AIRFLOW0105.DEV.ETL_METADATA_4
SET
  LAST_LOADED_DATE = (
    SELECT MAX(d.date)
    FROM AIRFLOW0105.DEV.FACT_STOCK_PRICE_4 f
    JOIN AIRFLOW0105.DEV.DIM_DATE_4 d
      ON f.date_sk = d.date_sk
  ),
  IS_INITIALIZED = TRUE,
  LAST_RUN_TS = CURRENT_TIMESTAMP()
WHERE JOB_NAME = 'stock_etl_4';